general:
  name: Spiking_Heidelberg_Digits
  data_dir: datasets/hdspikes

  time_window: 1 # 1 second
  num_channels: 700 # number of frequency channels

preprocess:
  create_val: False
  val_split: 0.1

graph:
  time_radius: 0.02
  channel_radius: 10

train:
  batch_size: 8
  num_workers: 8
  num_epochs: 100
  lr: 0.001
  weight_decay: 0.0001

model:
  num_classes: 20
  conv_channels: 128
  linear_channels: 128

